### ISSUE TITLE
Two initial errors

### ISSUE THREAD

**Issue by efmkoene** [kosmar2011/ImageInpaintingGatedConv-TF2#1]
Thanks so much for the ported code, it is super appreciated as I cannot easily run TF v1.x!

I ran into two (initial?) issues when trying to run the code on my own data. One error was that the `.../.../.../.../tmp/` led to errors further down the line, probably because this folder doesn't exist or isn't easily accessible... Anyhow, I simply removed this line to fix such errors.
https://github.com/kosmar2011/DeepFill-TF2/blob/8f9b12fda63d7209ade08f4b1ee761a0c0692c11/training.py#L58

The other is that a flag is required here
https://github.com/kosmar2011/DeepFill-TF2/blob/8f9b12fda63d7209ade08f4b1ee761a0c0692c11/training.py#L108
but it isn't supplied. I updated the `inpainting.yml` file accordingly with a line `gan_with_mask: False` (as setting it to True led to further errors of incompatible concatenations...).

Maybe add in the readme.MD that we also need to create the `CSV_loss`, `images_loss`, `images_examples`, and `training_checkpoints` folders.

Thanks again! :-)

**Comment by kosmar2011** [comment]
Hello! You are right, I have updated the README and the yaml file. For the cache it was specific to the pc I was working on so I changed it to inside the project. Thank you for using my code!
